CREATE DATABASE PRUEBATECNICA;
GO
USE PRUEBATECNICA;
GO
CREATE TABLE USUARIO(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Correo VARCHAR(100) UNIQUE,
	Clave VARCHAR(150)
);

GO

CREATE TABLE CLIENTE(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nombre VARCHAR(100),
	Dni VARCHAR(10) UNIQUE
);

GO

CREATE TABLE PEDIDOS(
	IdPedido INT PRIMARY KEY IDENTITY,
	Descripcion VARCHAR(100),
	IdCliente INT REFERENCES CLIENTE(IdCliente)
);

GO

CREATE PROCEDURE SP_INS_USUARIO
(@Correo VARCHAR(100), @Clave VARCHAR(150))
AS
BEGIN
	SET NOCOUNT ON
	INSERT INTO USUARIO(Correo, Clave) VALUES(@Correo, @Clave);
END;

GO

CREATE PROCEDURE SP_GET_LOGIN
(@Correo VARCHAR(100), @Clave VARCHAR(150), @IsValid BIT = 0 OUTPUT)
AS
BEGIN
	SET NOCOUNT ON
	SELECT @IsValid = 1 FROM USUARIO WHERE Correo = @Correo AND Clave = @Clave;
END;

GO

CREATE PROCEDURE SP_INS_CLIENTE
(@Nombre VARCHAR(100), @Dni VARCHAR(150))
AS
BEGIN
	SET NOCOUNT ON
	INSERT INTO CLIENTE(Nombre, Dni) VALUES(@Nombre, @Dni);
END;

GO

CREATE PROCEDURE SP_GET_PEDIDOS
(@IdPedido INT, @Dni VARCHAR(10))
AS
BEGIN
	SET NOCOUNT ON
	SELECT PED.IdPedido IdPedido, PED.Descripcion Descripcion FROM PEDIDOS PED
	INNER JOIN CLIENTE CLI ON CLI.IdCliente = PED.IdCliente
		WHERE (PED.IdPedido = @IdPedido OR CLI.Dni LIKE '%' + @Dni + '%') OR ( @IdPedido IS NULL AND @Dni IS NULL );
END;

GO

CREATE PROCEDURE SP_GET_PEDIDO
(@IdPedido INT)
AS
BEGIN
	SET NOCOUNT ON
	SELECT PED.IdPedido, PED.Descripcion, CLI.Nombre, CLI.Dni FROM PEDIDOS PED
	INNER JOIN CLIENTE CLI ON CLI.IdCliente = PED.IdCliente
		WHERE PED.IdPedido = @IdPedido;
END;

GO

CREATE PROCEDURE SP_INS_PEDIDOS
(@Descripcion VARCHAR(100), @IdCliente INT)
AS
BEGIN
	SET NOCOUNT ON
	INSERT INTO PEDIDOS(Descripcion, IdCliente) VALUES (@Descripcion, @IdCliente);
END;

GO

EXEC SP_INS_USUARIO 'ejemplo@prueba.com','123456789';

GO

EXEC SP_INS_CLIENTE 'Pedro','74851296';
EXEC SP_INS_CLIENTE 'Juan','75420315';
EXEC SP_INS_CLIENTE 'Lidia','78492612';
EXEC SP_INS_CLIENTE 'Vanessa','7012359';

GO

EXEC SP_INS_PEDIDOS 'Pedido Prueba 1 Pedro', 1;
EXEC SP_INS_PEDIDOS 'Pedido Prueba 2 Pedro', 1;
EXEC SP_INS_PEDIDOS 'Pedido Prueba 1 Juan', 2;
EXEC SP_INS_PEDIDOS 'Pedido Prueba 2 Juan', 2;
EXEC SP_INS_PEDIDOS 'Pedido Prueba 1 Lidia', 3;
EXEC SP_INS_PEDIDOS 'Pedido Prueba 2 Lidia', 3;
EXEC SP_INS_PEDIDOS 'Pedido Prueba 1 Vanessa', 4;
EXEC SP_INS_PEDIDOS 'Pedido Prueba 2 Vanessa', 4;

GO